language: node_js
node_js:
  - v10.17.0
cache:
  directories:
    - node_modules
  yarn: true
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - yarn run test:ganache
  - travis_retry yarn run test:truffle
notifications:
  kleros:
    slack: 'kleros:Ub8n81EgKJ3iRrMDyWyQIVJp'
